### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [ ]  Create html tree with car image
- [ ]  Style CSS to match image
- [ ]  Fix all errors

**Comment by John-Baik** [comment]
![image](https://user-images.githubusercontent.com/90541276/140409741-b854e69f-8457-472e-ad13-5dfb30c7a2bf.png)
