### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## HINT
-Create a simple data model that includes which way the car is facing, (north, south, east, or west).
-Listen for 'keydown' events on the document.

## ✅ Task List

- [ ]  Create classes for each direction. 
- [ ]  Select direction classes in CSS and assign the proper rotation for each selector
- [ ] Query Dom for arrow keys
- [ ]  Add event listener for each arrow key to assign the right direction.

**Comment by John-Baik** [comment]
https://camo.githubusercontent.com/c3ab3155ae64109a6263bf907dcdc570ef9b9404e88728cea8f65f3faad9469a/68747470733a2f2f6c667a2d7374617469632e73332d75732d776573742d312e616d617a6f6e6177732e636f6d2f67726170686963732f64656d6f732f64726976696e672d67616d652f757365722d63616e2d7475726e2d74686569722d6361722e676966

**Comment by John-Baik** [comment]
https://camo.githubusercontent.com/c3ab3155ae64109a6263bf907dcdc570ef9b9404e88728cea8f65f3faad9469a/68747470733a2f2f6c667a2d7374617469632e73332d75732d776573742d312e616d617a6f6e6177732e636f6d2f67726170686963732f64656d6f732f64726976696e672d67616d652f757365722d63616e2d7475726e2d74686569722d6361722e676966

**Comment by John-Baik** [comment]
![68747470733a2f2f6c667a2d7374617469632e73332d75732d776573742d312e616d617a6f6e6177732e636f6d2f67726170686963732f64656d6f732f64726976696e672d67616d652f757365722d63616e2d7475726e2d74686569722d6361722e676966](https://user-images.githubusercontent.com/90541276/140410370-554647c8-682f-41cc-9149-ec3088cda6d8.gif)
